name = "aesso-website"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "1c7ca0c1afd598a22989aa281b73b58c"

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true

# R2 bucket - temporarily disabled due to deployment issue
# [[r2_buckets]]
# binding = "R2_MEDIA"
# bucket_name = "aesso-media"

# KV namespace - remove comment if sessions are needed
# [[kv_namespaces]]
# binding = "SESSION"
# id = "0b7f2571ce964f23bb37c6cd7ab9691f"
# preview_id = "2331904ba0154ef1bac97d6dcc369812"
